[package]
name = "quicksort-rust"
version = "0.1.0"
authors = ["Jörg Matysiak <joemat@elinja.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
